### ISSUE TITLE
Bogus result returned by /api/state endpoint

### ISSUE THREAD

**Issue by spencermathews** [storiesofsolidarity/story-database#1]
https://app.storiesofsolidarity.org/api/state/?page=1

returns this item in the results array:

    {
        "abbr": null,
        "name": "",
        "story_count": 11,
        "preview": [
            "you all need to quit whining and learn to live within your means ...walmart is one of the greatest c",
            "There aren’t a lot of other opportunities here in Danville, Kentucky except Walmart.  Last month I",
            "I’ve worked at Walmart for almost 16 years. My last two years working at Walmart have been challeng"
        ]
    }

**Comment by jlev** [comment]
These are stories imported from the legacy database which do not have a location assigned. New stories created by SMS or user posting must have a location, and so this number will not grow. I consider this matter resolved.
